"""empty message

Revision ID: 4d719adff85f
Revises: 91f7d2a11dd6
Create Date: 2023-03-02 20:43:04.390963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d719adff85f'
down_revision = '91f7d2a11dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_uuid', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('unique_uuid', type_='unique')

    # ### end Alembic commands ###
